backend:
  name: github
  repo: johnhojohn969/cdn
  branch: main
  auth_type: pkce
  app_id: Ov2311oPTqfdQzfe2kR9

media_folder: "images"
public_folder: "/images"

collections:
  - name: uploads
    label: Uploads
    folder: "images"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
